name: build and deploy code
on: [push, pull_request]
jobs:
  job1:
    runs_on: ubuntu-latest
    steps:
      -name:pulling git repo
       uses:actions/checkout@v4
      -name:say hii to me
       run:echo"hello you"
